// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file student.proto (package student.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum student.v1.StudentStatus
 */
export enum StudentStatus {
  /**
   * @generated from enum value: STUDENT_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STUDENT_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: STUDENT_STATUS_INACTIVE = 2;
   */
  INACTIVE = 2,

  /**
   * @generated from enum value: STUDENT_STATUS_SUSPENDED = 3;
   */
  SUSPENDED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(StudentStatus)
proto3.util.setEnumType(StudentStatus, "student.v1.StudentStatus", [
  { no: 0, name: "STUDENT_STATUS_UNSPECIFIED" },
  { no: 1, name: "STUDENT_STATUS_ACTIVE" },
  { no: 2, name: "STUDENT_STATUS_INACTIVE" },
  { no: 3, name: "STUDENT_STATUS_SUSPENDED" },
]);

/**
 * @generated from message student.v1.Student
 */
export class Student extends Message<Student> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string first_name = 2;
   */
  firstName = "";

  /**
   * @generated from field: string last_name = 3;
   */
  lastName = "";

  /**
   * @generated from field: string email = 4;
   */
  email = "";

  /**
   * @generated from field: student.v1.StudentStatus status = 6;
   */
  status = StudentStatus.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<Student>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.Student";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "status", kind: "enum", T: proto3.getEnumType(StudentStatus) },
    { no: 7, name: "created_at", kind: "message", T: Timestamp },
    { no: 8, name: "updated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Student {
    return new Student().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Student {
    return new Student().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Student {
    return new Student().fromJsonString(jsonString, options);
  }

  static equals(a: Student | PlainMessage<Student> | undefined, b: Student | PlainMessage<Student> | undefined): boolean {
    return proto3.util.equals(Student, a, b);
  }
}

/**
 * @generated from message student.v1.CreateStudentRequest
 */
export class CreateStudentRequest extends Message<CreateStudentRequest> {
  /**
   * @generated from field: string first_name = 1;
   */
  firstName = "";

  /**
   * @generated from field: string last_name = 2;
   */
  lastName = "";

  /**
   * @generated from field: string email = 3;
   */
  email = "";

  constructor(data?: PartialMessage<CreateStudentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.CreateStudentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateStudentRequest {
    return new CreateStudentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateStudentRequest {
    return new CreateStudentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateStudentRequest {
    return new CreateStudentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateStudentRequest | PlainMessage<CreateStudentRequest> | undefined, b: CreateStudentRequest | PlainMessage<CreateStudentRequest> | undefined): boolean {
    return proto3.util.equals(CreateStudentRequest, a, b);
  }
}

/**
 * @generated from message student.v1.CreateStudentResponse
 */
export class CreateStudentResponse extends Message<CreateStudentResponse> {
  /**
   * @generated from field: student.v1.Student student = 1;
   */
  student?: Student;

  constructor(data?: PartialMessage<CreateStudentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.CreateStudentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "student", kind: "message", T: Student },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateStudentResponse {
    return new CreateStudentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateStudentResponse {
    return new CreateStudentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateStudentResponse {
    return new CreateStudentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateStudentResponse | PlainMessage<CreateStudentResponse> | undefined, b: CreateStudentResponse | PlainMessage<CreateStudentResponse> | undefined): boolean {
    return proto3.util.equals(CreateStudentResponse, a, b);
  }
}

/**
 * @generated from message student.v1.GetStudentRequest
 */
export class GetStudentRequest extends Message<GetStudentRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<GetStudentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.GetStudentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStudentRequest {
    return new GetStudentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStudentRequest {
    return new GetStudentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStudentRequest {
    return new GetStudentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetStudentRequest | PlainMessage<GetStudentRequest> | undefined, b: GetStudentRequest | PlainMessage<GetStudentRequest> | undefined): boolean {
    return proto3.util.equals(GetStudentRequest, a, b);
  }
}

/**
 * @generated from message student.v1.GetStudentResponse
 */
export class GetStudentResponse extends Message<GetStudentResponse> {
  /**
   * @generated from field: student.v1.Student student = 1;
   */
  student?: Student;

  constructor(data?: PartialMessage<GetStudentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.GetStudentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "student", kind: "message", T: Student },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStudentResponse {
    return new GetStudentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStudentResponse {
    return new GetStudentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStudentResponse {
    return new GetStudentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetStudentResponse | PlainMessage<GetStudentResponse> | undefined, b: GetStudentResponse | PlainMessage<GetStudentResponse> | undefined): boolean {
    return proto3.util.equals(GetStudentResponse, a, b);
  }
}

/**
 * @generated from message student.v1.UpdateStudentRequest
 */
export class UpdateStudentRequest extends Message<UpdateStudentRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: optional string first_name = 2;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 3;
   */
  lastName?: string;

  /**
   * @generated from field: optional string email = 4;
   */
  email?: string;

  /**
   * @generated from field: optional int32 age = 5;
   */
  age?: number;

  /**
   * @generated from field: optional student.v1.StudentStatus status = 6;
   */
  status?: StudentStatus;

  constructor(data?: PartialMessage<UpdateStudentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.UpdateStudentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "age", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "status", kind: "enum", T: proto3.getEnumType(StudentStatus), opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateStudentRequest {
    return new UpdateStudentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateStudentRequest {
    return new UpdateStudentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateStudentRequest {
    return new UpdateStudentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateStudentRequest | PlainMessage<UpdateStudentRequest> | undefined, b: UpdateStudentRequest | PlainMessage<UpdateStudentRequest> | undefined): boolean {
    return proto3.util.equals(UpdateStudentRequest, a, b);
  }
}

/**
 * @generated from message student.v1.UpdateStudentResponse
 */
export class UpdateStudentResponse extends Message<UpdateStudentResponse> {
  /**
   * @generated from field: student.v1.Student student = 1;
   */
  student?: Student;

  constructor(data?: PartialMessage<UpdateStudentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.UpdateStudentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "student", kind: "message", T: Student },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateStudentResponse {
    return new UpdateStudentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateStudentResponse {
    return new UpdateStudentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateStudentResponse {
    return new UpdateStudentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateStudentResponse | PlainMessage<UpdateStudentResponse> | undefined, b: UpdateStudentResponse | PlainMessage<UpdateStudentResponse> | undefined): boolean {
    return proto3.util.equals(UpdateStudentResponse, a, b);
  }
}

/**
 * @generated from message student.v1.DeleteStudentRequest
 */
export class DeleteStudentRequest extends Message<DeleteStudentRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<DeleteStudentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.DeleteStudentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteStudentRequest {
    return new DeleteStudentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteStudentRequest {
    return new DeleteStudentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteStudentRequest {
    return new DeleteStudentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteStudentRequest | PlainMessage<DeleteStudentRequest> | undefined, b: DeleteStudentRequest | PlainMessage<DeleteStudentRequest> | undefined): boolean {
    return proto3.util.equals(DeleteStudentRequest, a, b);
  }
}

/**
 * @generated from message student.v1.DeleteStudentResponse
 */
export class DeleteStudentResponse extends Message<DeleteStudentResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<DeleteStudentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.DeleteStudentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteStudentResponse {
    return new DeleteStudentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteStudentResponse {
    return new DeleteStudentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteStudentResponse {
    return new DeleteStudentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteStudentResponse | PlainMessage<DeleteStudentResponse> | undefined, b: DeleteStudentResponse | PlainMessage<DeleteStudentResponse> | undefined): boolean {
    return proto3.util.equals(DeleteStudentResponse, a, b);
  }
}

/**
 * @generated from message student.v1.ListStudentsRequest
 */
export class ListStudentsRequest extends Message<ListStudentsRequest> {
  /**
   * @generated from field: int32 page = 1;
   */
  page = 0;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  /**
   * @generated from field: optional student.v1.StudentStatus status = 3;
   */
  status?: StudentStatus;

  constructor(data?: PartialMessage<ListStudentsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.ListStudentsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "status", kind: "enum", T: proto3.getEnumType(StudentStatus), opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListStudentsRequest {
    return new ListStudentsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListStudentsRequest {
    return new ListStudentsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListStudentsRequest {
    return new ListStudentsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListStudentsRequest | PlainMessage<ListStudentsRequest> | undefined, b: ListStudentsRequest | PlainMessage<ListStudentsRequest> | undefined): boolean {
    return proto3.util.equals(ListStudentsRequest, a, b);
  }
}

/**
 * @generated from message student.v1.Pagination
 */
export class Pagination extends Message<Pagination> {
  /**
   * @generated from field: int32 page = 1;
   */
  page = 0;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  /**
   * @generated from field: int32 total = 3;
   */
  total = 0;

  /**
   * @generated from field: int32 total_pages = 4;
   */
  totalPages = 0;

  constructor(data?: PartialMessage<Pagination>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.Pagination";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "total_pages", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Pagination {
    return new Pagination().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Pagination {
    return new Pagination().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Pagination {
    return new Pagination().fromJsonString(jsonString, options);
  }

  static equals(a: Pagination | PlainMessage<Pagination> | undefined, b: Pagination | PlainMessage<Pagination> | undefined): boolean {
    return proto3.util.equals(Pagination, a, b);
  }
}

/**
 * @generated from message student.v1.ListStudentsResponse
 */
export class ListStudentsResponse extends Message<ListStudentsResponse> {
  /**
   * @generated from field: repeated student.v1.Student data = 1;
   */
  data: Student[] = [];

  /**
   * @generated from field: student.v1.Pagination pagination = 2;
   */
  pagination?: Pagination;

  constructor(data?: PartialMessage<ListStudentsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.ListStudentsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "message", T: Student, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: Pagination },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListStudentsResponse {
    return new ListStudentsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListStudentsResponse {
    return new ListStudentsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListStudentsResponse {
    return new ListStudentsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListStudentsResponse | PlainMessage<ListStudentsResponse> | undefined, b: ListStudentsResponse | PlainMessage<ListStudentsResponse> | undefined): boolean {
    return proto3.util.equals(ListStudentsResponse, a, b);
  }
}

/**
 * @generated from message student.v1.MakePaymentRequest
 */
export class MakePaymentRequest extends Message<MakePaymentRequest> {
  /**
   * @generated from field: int64 student_id = 1;
   */
  studentId = protoInt64.zero;

  /**
   * @generated from field: double amount = 2;
   */
  amount = 0;

  /**
   * @generated from field: string reference = 3;
   */
  reference = "";

  constructor(data?: PartialMessage<MakePaymentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.MakePaymentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "student_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "amount", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "reference", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MakePaymentRequest {
    return new MakePaymentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MakePaymentRequest {
    return new MakePaymentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MakePaymentRequest {
    return new MakePaymentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MakePaymentRequest | PlainMessage<MakePaymentRequest> | undefined, b: MakePaymentRequest | PlainMessage<MakePaymentRequest> | undefined): boolean {
    return proto3.util.equals(MakePaymentRequest, a, b);
  }
}

/**
 * @generated from message student.v1.MakePaymentResponse
 */
export class MakePaymentResponse extends Message<MakePaymentResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<MakePaymentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "student.v1.MakePaymentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MakePaymentResponse {
    return new MakePaymentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MakePaymentResponse {
    return new MakePaymentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MakePaymentResponse {
    return new MakePaymentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MakePaymentResponse | PlainMessage<MakePaymentResponse> | undefined, b: MakePaymentResponse | PlainMessage<MakePaymentResponse> | undefined): boolean {
    return proto3.util.equals(MakePaymentResponse, a, b);
  }
}

