# When using posgres it will can replica to multiple coZ now it will create a sqlite file on all node  

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - micro-network
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    deploy:
      replicas: 1

  redis:
    image: redis:alpine
    networks:
      - micro-network
    deploy:
      replicas: 1

  student:
    image: my-registry/student-service:latest
    build: ./services/student
    networks:
      - micro-network
    environment:
      - DATABASE_URL=sqlite:///./users.db
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    command: [ "uv", "run", "fastapi", "run", "main.py", "--port", "8000", "--host", "0.0.0.0" ]
    deploy:
      replicas: 1

  payment:
    image: my-registry/payment-service:latest
    build: ./services/payment
    networks:
      - micro-network
    environment:
      - DATABASE_URL=sqlite:///./payments.db
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    command: [ "uv", "run", "fastapi", "run", "main.py", "--port", "8002", "--host", "0.0.0.0", "--workers", "4" ]
    deploy:
      replicas: 1

  notification:
    image: my-registry/notification-service:latest
    build: ./services/notification
    networks:
      - micro-network
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    command: [ "uv", "run", "fastapi", "run", "main.py", "--port", "8005", "--host", "0.0.0.0" ]
    deploy:
      replicas: 1

  auth:
    image: my-registry/auth-service:latest
    build: ./services/auth
    networks:
      - micro-network
    environment:
      - JWT_SECRET=super-secret-key
    command: [ "bun", "run", "src/index.ts" ]
    deploy:
      replicas: 1

  gateway:
    image: my-registry/gateway:latest
    build: ./gateway
    networks:
      - micro-network
    environment:
      - USER_SERVICE_URL=http://student:8000/connect
      - PAYMENT_SERVICE_URL=http://payment:8002/connect
      - AUTH_SERVICE_URL=http://auth:8001
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    command: [ "bun", "run", "start" ]
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s

  ui:
    image: my-registry/ui:latest
    build: ./ui
    networks:
      - micro-network
    environment:
      - VITE_API_URL=/api
    deploy:
      replicas: 1

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - micro-network
    depends_on:
      - ui
      - gateway

networks:
  micro-network:
    driver: overlay
