services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  student:
    build: ./api/services/student
    container_name: student_service
    ports:
      - "8000:8000"
    volumes:
      - ./api/services/student:/app
    environment:
      - DATABASE_URL=sqlite:///./users.db
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    command:
      [
        "uv",
        "run",
        "fastapi",
        "dev",
        "main.py",
        "--port",
        "8000",
        "--host",
        "0.0.0.0",
      ]
    depends_on:
      - rabbitmq

  payment:
    build: ./api/services/payment
    container_name: payment_service
    ports:
      - "8002:8002"
    volumes:
      - ./api/services/payment:/app
    environment:
      - DATABASE_URL=sqlite:///./payments.db
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    command:
      [
        "uv",
        "run",
        "fastapi",
        "run",
        "main.py",
        "--port",
        "8002",
        "--host",
        "0.0.0.0",
        "--workers",
        "5",
      ]
    depends_on:
      - rabbitmq

  notification:
    build: ./api/services/notification
    container_name: notification_service
    ports:
      - "8005:8005"
    volumes:
      - ./api/services/notification:/app
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    command:
      [
        "uv",
        "run",
        "fastapi",
        "dev",
        "main.py",
        "--port",
        "8005",
        "--host",
        "0.0.0.0",
      ]
    depends_on:
      - rabbitmq

  auth:
    build: ./api/services/auth
    container_name: auth_service
    ports:
      - "8001:8001"
    volumes:
      - ./api/services/auth:/app
      - /app/node_modules
    environment:
      - JWT_SECRET=super-secret-key
    command: ["bun", "run", "dev"]

  gateway:
    build: ./api/gateway
    container_name: gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api/gateway:/app
      - /app/node_modules
    environment:
      - USER_SERVICE_URL=http://student:8000/connect
      - PAYMENT_SERVICE_URL=http://payment:8002/connect
      - AUTH_SERVICE_URL=http://auth:8001
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    command: ["bun", "run", "dev"]
    depends_on:
      - rabbitmq
      - redis
      - student
      - payment

  ui:
    build: ./ui
    container_name: react_ui
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - gateway
