# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: auth.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from . import auth_pb2 as auth__pb2


class AuthService(Protocol):
    async def login(self, request: auth__pb2.LoginRequest, ctx: RequestContext) -> auth__pb2.LoginResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def register(self, request: auth__pb2.RegisterRequest, ctx: RequestContext) -> auth__pb2.RegisterResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def verify(self, request: auth__pb2.VerifyRequest, ctx: RequestContext) -> auth__pb2.VerifyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AuthServiceASGIApplication(ConnectASGIApplication[AuthService]):
    def __init__(self, service: AuthService | AsyncGenerator[AuthService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/auth.v1.AuthService/Login": Endpoint.unary(
                    method=MethodInfo(
                        name="Login",
                        service_name="auth.v1.AuthService",
                        input=auth__pb2.LoginRequest,
                        output=auth__pb2.LoginResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.login,
                ),
                "/auth.v1.AuthService/Register": Endpoint.unary(
                    method=MethodInfo(
                        name="Register",
                        service_name="auth.v1.AuthService",
                        input=auth__pb2.RegisterRequest,
                        output=auth__pb2.RegisterResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.register,
                ),
                "/auth.v1.AuthService/Verify": Endpoint.unary(
                    method=MethodInfo(
                        name="Verify",
                        service_name="auth.v1.AuthService",
                        input=auth__pb2.VerifyRequest,
                        output=auth__pb2.VerifyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.verify,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/auth.v1.AuthService"


class AuthServiceClient(ConnectClient):
    async def login(
        self,
        request: auth__pb2.LoginRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> auth__pb2.LoginResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Login",
                service_name="auth.v1.AuthService",
                input=auth__pb2.LoginRequest,
                output=auth__pb2.LoginResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def register(
        self,
        request: auth__pb2.RegisterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> auth__pb2.RegisterResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Register",
                service_name="auth.v1.AuthService",
                input=auth__pb2.RegisterRequest,
                output=auth__pb2.RegisterResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def verify(
        self,
        request: auth__pb2.VerifyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> auth__pb2.VerifyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Verify",
                service_name="auth.v1.AuthService",
                input=auth__pb2.VerifyRequest,
                output=auth__pb2.VerifyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class AuthServiceSync(Protocol):
    def login(self, request: auth__pb2.LoginRequest, ctx: RequestContext) -> auth__pb2.LoginResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def register(self, request: auth__pb2.RegisterRequest, ctx: RequestContext) -> auth__pb2.RegisterResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def verify(self, request: auth__pb2.VerifyRequest, ctx: RequestContext) -> auth__pb2.VerifyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AuthServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AuthServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/auth.v1.AuthService/Login": EndpointSync.unary(
                    method=MethodInfo(
                        name="Login",
                        service_name="auth.v1.AuthService",
                        input=auth__pb2.LoginRequest,
                        output=auth__pb2.LoginResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.login,
                ),
                "/auth.v1.AuthService/Register": EndpointSync.unary(
                    method=MethodInfo(
                        name="Register",
                        service_name="auth.v1.AuthService",
                        input=auth__pb2.RegisterRequest,
                        output=auth__pb2.RegisterResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.register,
                ),
                "/auth.v1.AuthService/Verify": EndpointSync.unary(
                    method=MethodInfo(
                        name="Verify",
                        service_name="auth.v1.AuthService",
                        input=auth__pb2.VerifyRequest,
                        output=auth__pb2.VerifyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.verify,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/auth.v1.AuthService"


class AuthServiceClientSync(ConnectClientSync):
    def login(
        self,
        request: auth__pb2.LoginRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> auth__pb2.LoginResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Login",
                service_name="auth.v1.AuthService",
                input=auth__pb2.LoginRequest,
                output=auth__pb2.LoginResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def register(
        self,
        request: auth__pb2.RegisterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> auth__pb2.RegisterResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Register",
                service_name="auth.v1.AuthService",
                input=auth__pb2.RegisterRequest,
                output=auth__pb2.RegisterResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def verify(
        self,
        request: auth__pb2.VerifyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> auth__pb2.VerifyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Verify",
                service_name="auth.v1.AuthService",
                input=auth__pb2.VerifyRequest,
                output=auth__pb2.VerifyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


