# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\npayment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x02\n\x07Payment\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n\nstudent_id\x18\x02 \x01(\x03R\tstudentId\x12\x16\n\x06\x61mount\x18\x03 \x01(\x01R\x06\x61mount\x12\x1c\n\treference\x18\x04 \x01(\tR\treference\x12\x16\n\x06status\x18\x05 \x01(\tR\x06status\x12*\n\x0etransaction_id\x18\x06 \x01(\tH\x00R\rtransactionId\x88\x01\x01\x12\x39\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x39\n\nupdated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tupdatedAtB\x11\n\x0f_transaction_id\"H\n\x13ListPaymentsRequest\x12\"\n\nstudent_id\x18\x01 \x01(\x03H\x00R\tstudentId\x88\x01\x01\x42\r\n\x0b_student_id\"?\n\x14ListPaymentsResponse\x12\'\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.payment.v1.PaymentR\x04\x64\x61ta2c\n\x0ePaymentService\x12Q\n\x0cListPayments\x12\x1f.payment.v1.ListPaymentsRequest\x1a .payment.v1.ListPaymentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENT']._serialized_start=63
  _globals['_PAYMENT']._serialized_end=378
  _globals['_LISTPAYMENTSREQUEST']._serialized_start=380
  _globals['_LISTPAYMENTSREQUEST']._serialized_end=452
  _globals['_LISTPAYMENTSRESPONSE']._serialized_start=454
  _globals['_LISTPAYMENTSRESPONSE']._serialized_end=517
  _globals['_PAYMENTSERVICE']._serialized_start=519
  _globals['_PAYMENTSERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
