# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: student.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from . import student_pb2 as student__pb2


class StudentService(Protocol):
    async def create_student(self, request: student__pb2.CreateStudentRequest, ctx: RequestContext) -> student__pb2.CreateStudentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_student(self, request: student__pb2.GetStudentRequest, ctx: RequestContext) -> student__pb2.GetStudentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_student(self, request: student__pb2.UpdateStudentRequest, ctx: RequestContext) -> student__pb2.UpdateStudentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_student(self, request: student__pb2.DeleteStudentRequest, ctx: RequestContext) -> student__pb2.DeleteStudentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_students(self, request: student__pb2.ListStudentsRequest, ctx: RequestContext) -> student__pb2.ListStudentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def make_payment(self, request: student__pb2.MakePaymentRequest, ctx: RequestContext) -> student__pb2.MakePaymentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class StudentServiceASGIApplication(ConnectASGIApplication[StudentService]):
    def __init__(self, service: StudentService | AsyncGenerator[StudentService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/student.v1.StudentService/CreateStudent": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateStudent",
                        service_name="student.v1.StudentService",
                        input=student__pb2.CreateStudentRequest,
                        output=student__pb2.CreateStudentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_student,
                ),
                "/student.v1.StudentService/GetStudent": Endpoint.unary(
                    method=MethodInfo(
                        name="GetStudent",
                        service_name="student.v1.StudentService",
                        input=student__pb2.GetStudentRequest,
                        output=student__pb2.GetStudentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_student,
                ),
                "/student.v1.StudentService/UpdateStudent": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateStudent",
                        service_name="student.v1.StudentService",
                        input=student__pb2.UpdateStudentRequest,
                        output=student__pb2.UpdateStudentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_student,
                ),
                "/student.v1.StudentService/DeleteStudent": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteStudent",
                        service_name="student.v1.StudentService",
                        input=student__pb2.DeleteStudentRequest,
                        output=student__pb2.DeleteStudentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_student,
                ),
                "/student.v1.StudentService/ListStudents": Endpoint.unary(
                    method=MethodInfo(
                        name="ListStudents",
                        service_name="student.v1.StudentService",
                        input=student__pb2.ListStudentsRequest,
                        output=student__pb2.ListStudentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_students,
                ),
                "/student.v1.StudentService/MakePayment": Endpoint.unary(
                    method=MethodInfo(
                        name="MakePayment",
                        service_name="student.v1.StudentService",
                        input=student__pb2.MakePaymentRequest,
                        output=student__pb2.MakePaymentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.make_payment,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/student.v1.StudentService"


class StudentServiceClient(ConnectClient):
    async def create_student(
        self,
        request: student__pb2.CreateStudentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.CreateStudentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateStudent",
                service_name="student.v1.StudentService",
                input=student__pb2.CreateStudentRequest,
                output=student__pb2.CreateStudentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_student(
        self,
        request: student__pb2.GetStudentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.GetStudentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStudent",
                service_name="student.v1.StudentService",
                input=student__pb2.GetStudentRequest,
                output=student__pb2.GetStudentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_student(
        self,
        request: student__pb2.UpdateStudentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.UpdateStudentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateStudent",
                service_name="student.v1.StudentService",
                input=student__pb2.UpdateStudentRequest,
                output=student__pb2.UpdateStudentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_student(
        self,
        request: student__pb2.DeleteStudentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.DeleteStudentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteStudent",
                service_name="student.v1.StudentService",
                input=student__pb2.DeleteStudentRequest,
                output=student__pb2.DeleteStudentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_students(
        self,
        request: student__pb2.ListStudentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.ListStudentsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStudents",
                service_name="student.v1.StudentService",
                input=student__pb2.ListStudentsRequest,
                output=student__pb2.ListStudentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def make_payment(
        self,
        request: student__pb2.MakePaymentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.MakePaymentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MakePayment",
                service_name="student.v1.StudentService",
                input=student__pb2.MakePaymentRequest,
                output=student__pb2.MakePaymentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class StudentServiceSync(Protocol):
    def create_student(self, request: student__pb2.CreateStudentRequest, ctx: RequestContext) -> student__pb2.CreateStudentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_student(self, request: student__pb2.GetStudentRequest, ctx: RequestContext) -> student__pb2.GetStudentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_student(self, request: student__pb2.UpdateStudentRequest, ctx: RequestContext) -> student__pb2.UpdateStudentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_student(self, request: student__pb2.DeleteStudentRequest, ctx: RequestContext) -> student__pb2.DeleteStudentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_students(self, request: student__pb2.ListStudentsRequest, ctx: RequestContext) -> student__pb2.ListStudentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def make_payment(self, request: student__pb2.MakePaymentRequest, ctx: RequestContext) -> student__pb2.MakePaymentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class StudentServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: StudentServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/student.v1.StudentService/CreateStudent": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateStudent",
                        service_name="student.v1.StudentService",
                        input=student__pb2.CreateStudentRequest,
                        output=student__pb2.CreateStudentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_student,
                ),
                "/student.v1.StudentService/GetStudent": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetStudent",
                        service_name="student.v1.StudentService",
                        input=student__pb2.GetStudentRequest,
                        output=student__pb2.GetStudentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_student,
                ),
                "/student.v1.StudentService/UpdateStudent": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateStudent",
                        service_name="student.v1.StudentService",
                        input=student__pb2.UpdateStudentRequest,
                        output=student__pb2.UpdateStudentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_student,
                ),
                "/student.v1.StudentService/DeleteStudent": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteStudent",
                        service_name="student.v1.StudentService",
                        input=student__pb2.DeleteStudentRequest,
                        output=student__pb2.DeleteStudentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_student,
                ),
                "/student.v1.StudentService/ListStudents": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListStudents",
                        service_name="student.v1.StudentService",
                        input=student__pb2.ListStudentsRequest,
                        output=student__pb2.ListStudentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_students,
                ),
                "/student.v1.StudentService/MakePayment": EndpointSync.unary(
                    method=MethodInfo(
                        name="MakePayment",
                        service_name="student.v1.StudentService",
                        input=student__pb2.MakePaymentRequest,
                        output=student__pb2.MakePaymentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.make_payment,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/student.v1.StudentService"


class StudentServiceClientSync(ConnectClientSync):
    def create_student(
        self,
        request: student__pb2.CreateStudentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.CreateStudentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateStudent",
                service_name="student.v1.StudentService",
                input=student__pb2.CreateStudentRequest,
                output=student__pb2.CreateStudentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_student(
        self,
        request: student__pb2.GetStudentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.GetStudentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStudent",
                service_name="student.v1.StudentService",
                input=student__pb2.GetStudentRequest,
                output=student__pb2.GetStudentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_student(
        self,
        request: student__pb2.UpdateStudentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.UpdateStudentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateStudent",
                service_name="student.v1.StudentService",
                input=student__pb2.UpdateStudentRequest,
                output=student__pb2.UpdateStudentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_student(
        self,
        request: student__pb2.DeleteStudentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.DeleteStudentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteStudent",
                service_name="student.v1.StudentService",
                input=student__pb2.DeleteStudentRequest,
                output=student__pb2.DeleteStudentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_students(
        self,
        request: student__pb2.ListStudentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.ListStudentsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStudents",
                service_name="student.v1.StudentService",
                input=student__pb2.ListStudentsRequest,
                output=student__pb2.ListStudentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def make_payment(
        self,
        request: student__pb2.MakePaymentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> student__pb2.MakePaymentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MakePayment",
                service_name="student.v1.StudentService",
                input=student__pb2.MakePaymentRequest,
                output=student__pb2.MakePaymentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


