syntax = "proto3";

package auth.v1;

service AuthService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Verify(VerifyRequest) returns (VerifyResponse);
}

message AuthUser {
  int32 id = 1;
  string email = 2;
  string role = 3;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  bool success = 1;
  string token = 2;
  optional AuthUser user = 3;
}

message RegisterRequest {
  string email = 1;
  string password = 2;
}

message RegisterResponse {
  bool success = 1;
  optional AuthUser user = 2;
}

message VerifyRequest {
  string token = 1;
}

message VerifyResponse {
  bool valid = 1;
  optional AuthUser user = 2;
}
