// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LoginRequest, LoginResponse, RegisterRequest, RegisterResponse, VerifyRequest, VerifyResponse } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service auth.v1.AuthService
 */
export const AuthService = {
  typeName: "auth.v1.AuthService",
  methods: {
    /**
     * @generated from rpc auth.v1.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.Verify
     */
    verify: {
      name: "Verify",
      I: VerifyRequest,
      O: VerifyResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

