// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file payment.proto (package payment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message payment.v1.Payment
 */
export class Payment extends Message<Payment> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: int64 student_id = 2;
   */
  studentId = protoInt64.zero;

  /**
   * @generated from field: double amount = 3;
   */
  amount = 0;

  /**
   * @generated from field: string reference = 4;
   */
  reference = "";

  /**
   * @generated from field: string status = 5;
   */
  status = "";

  /**
   * @generated from field: optional string transaction_id = 6;
   */
  transactionId?: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<Payment>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "payment.v1.Payment";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "student_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "amount", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "reference", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "created_at", kind: "message", T: Timestamp },
    { no: 8, name: "updated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Payment {
    return new Payment().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Payment {
    return new Payment().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Payment {
    return new Payment().fromJsonString(jsonString, options);
  }

  static equals(a: Payment | PlainMessage<Payment> | undefined, b: Payment | PlainMessage<Payment> | undefined): boolean {
    return proto3.util.equals(Payment, a, b);
  }
}

/**
 * @generated from message payment.v1.ListPaymentsRequest
 */
export class ListPaymentsRequest extends Message<ListPaymentsRequest> {
  /**
   * @generated from field: optional int64 student_id = 1;
   */
  studentId?: bigint;

  constructor(data?: PartialMessage<ListPaymentsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "payment.v1.ListPaymentsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "student_id", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPaymentsRequest {
    return new ListPaymentsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPaymentsRequest {
    return new ListPaymentsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPaymentsRequest {
    return new ListPaymentsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListPaymentsRequest | PlainMessage<ListPaymentsRequest> | undefined, b: ListPaymentsRequest | PlainMessage<ListPaymentsRequest> | undefined): boolean {
    return proto3.util.equals(ListPaymentsRequest, a, b);
  }
}

/**
 * @generated from message payment.v1.ListPaymentsResponse
 */
export class ListPaymentsResponse extends Message<ListPaymentsResponse> {
  /**
   * @generated from field: repeated payment.v1.Payment data = 1;
   */
  data: Payment[] = [];

  constructor(data?: PartialMessage<ListPaymentsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "payment.v1.ListPaymentsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "message", T: Payment, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPaymentsResponse {
    return new ListPaymentsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPaymentsResponse {
    return new ListPaymentsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPaymentsResponse {
    return new ListPaymentsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListPaymentsResponse | PlainMessage<ListPaymentsResponse> | undefined, b: ListPaymentsResponse | PlainMessage<ListPaymentsResponse> | undefined): boolean {
    return proto3.util.equals(ListPaymentsResponse, a, b);
  }
}

