// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file payment.proto (package payment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListPaymentsRequest, ListPaymentsResponse } from "./payment_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service payment.v1.PaymentService
 */
export const PaymentService = {
  typeName: "payment.v1.PaymentService",
  methods: {
    /**
     * @generated from rpc payment.v1.PaymentService.ListPayments
     */
    listPayments: {
      name: "ListPayments",
      I: ListPaymentsRequest,
      O: ListPaymentsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

