// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file student.proto (package student.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateStudentRequest, CreateStudentResponse, DeleteStudentRequest, DeleteStudentResponse, GetStudentRequest, GetStudentResponse, ListStudentsRequest, ListStudentsResponse, MakePaymentRequest, MakePaymentResponse, UpdateStudentRequest, UpdateStudentResponse } from "./student_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service student.v1.StudentService
 */
export const StudentService = {
  typeName: "student.v1.StudentService",
  methods: {
    /**
     * @generated from rpc student.v1.StudentService.CreateStudent
     */
    createStudent: {
      name: "CreateStudent",
      I: CreateStudentRequest,
      O: CreateStudentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc student.v1.StudentService.GetStudent
     */
    getStudent: {
      name: "GetStudent",
      I: GetStudentRequest,
      O: GetStudentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc student.v1.StudentService.UpdateStudent
     */
    updateStudent: {
      name: "UpdateStudent",
      I: UpdateStudentRequest,
      O: UpdateStudentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc student.v1.StudentService.DeleteStudent
     */
    deleteStudent: {
      name: "DeleteStudent",
      I: DeleteStudentRequest,
      O: DeleteStudentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc student.v1.StudentService.ListStudents
     */
    listStudents: {
      name: "ListStudents",
      I: ListStudentsRequest,
      O: ListStudentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc student.v1.StudentService.MakePayment
     */
    makePayment: {
      name: "MakePayment",
      I: MakePaymentRequest,
      O: MakePaymentResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

