# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x07\x61uth.v1\"D\n\x08\x41uthUser\x12\x0e\n\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n\x05\x65mail\x18\x02 \x01(\tR\x05\x65mail\x12\x12\n\x04role\x18\x03 \x01(\tR\x04role\"@\n\x0cLoginRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\"t\n\rLoginResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x14\n\x05token\x18\x02 \x01(\tR\x05token\x12*\n\x04user\x18\x03 \x01(\x0b\x32\x11.auth.v1.AuthUserH\x00R\x04user\x88\x01\x01\x42\x07\n\x05_user\"C\n\x0fRegisterRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\"a\n\x10RegisterResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12*\n\x04user\x18\x02 \x01(\x0b\x32\x11.auth.v1.AuthUserH\x00R\x04user\x88\x01\x01\x42\x07\n\x05_user\"%\n\rVerifyRequest\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\"[\n\x0eVerifyResponse\x12\x14\n\x05valid\x18\x01 \x01(\x08R\x05valid\x12*\n\x04user\x18\x02 \x01(\x0b\x32\x11.auth.v1.AuthUserH\x00R\x04user\x88\x01\x01\x42\x07\n\x05_user2\xc1\x01\n\x0b\x41uthService\x12\x36\n\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\x12?\n\x08Register\x12\x18.auth.v1.RegisterRequest\x1a\x19.auth.v1.RegisterResponse\x12\x39\n\x06Verify\x12\x16.auth.v1.VerifyRequest\x1a\x17.auth.v1.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHUSER']._serialized_start=23
  _globals['_AUTHUSER']._serialized_end=91
  _globals['_LOGINREQUEST']._serialized_start=93
  _globals['_LOGINREQUEST']._serialized_end=157
  _globals['_LOGINRESPONSE']._serialized_start=159
  _globals['_LOGINRESPONSE']._serialized_end=275
  _globals['_REGISTERREQUEST']._serialized_start=277
  _globals['_REGISTERREQUEST']._serialized_end=344
  _globals['_REGISTERRESPONSE']._serialized_start=346
  _globals['_REGISTERRESPONSE']._serialized_end=443
  _globals['_VERIFYREQUEST']._serialized_start=445
  _globals['_VERIFYREQUEST']._serialized_end=482
  _globals['_VERIFYRESPONSE']._serialized_start=484
  _globals['_VERIFYRESPONSE']._serialized_end=575
  _globals['_AUTHSERVICE']._serialized_start=578
  _globals['_AUTHSERVICE']._serialized_end=771
# @@protoc_insertion_point(module_scope)
