# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: payment.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from . import payment_pb2 as payment__pb2


class PaymentService(Protocol):
    async def list_payments(self, request: payment__pb2.ListPaymentsRequest, ctx: RequestContext) -> payment__pb2.ListPaymentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PaymentServiceASGIApplication(ConnectASGIApplication[PaymentService]):
    def __init__(self, service: PaymentService | AsyncGenerator[PaymentService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/payment.v1.PaymentService/ListPayments": Endpoint.unary(
                    method=MethodInfo(
                        name="ListPayments",
                        service_name="payment.v1.PaymentService",
                        input=payment__pb2.ListPaymentsRequest,
                        output=payment__pb2.ListPaymentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_payments,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/payment.v1.PaymentService"


class PaymentServiceClient(ConnectClient):
    async def list_payments(
        self,
        request: payment__pb2.ListPaymentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> payment__pb2.ListPaymentsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPayments",
                service_name="payment.v1.PaymentService",
                input=payment__pb2.ListPaymentsRequest,
                output=payment__pb2.ListPaymentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class PaymentServiceSync(Protocol):
    def list_payments(self, request: payment__pb2.ListPaymentsRequest, ctx: RequestContext) -> payment__pb2.ListPaymentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PaymentServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: PaymentServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/payment.v1.PaymentService/ListPayments": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListPayments",
                        service_name="payment.v1.PaymentService",
                        input=payment__pb2.ListPaymentsRequest,
                        output=payment__pb2.ListPaymentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_payments,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/payment.v1.PaymentService"


class PaymentServiceClientSync(ConnectClientSync):
    def list_payments(
        self,
        request: payment__pb2.ListPaymentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> payment__pb2.ListPaymentsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPayments",
                service_name="payment.v1.PaymentService",
                input=payment__pb2.ListPaymentsRequest,
                output=payment__pb2.ListPaymentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


